version: "3.8"
services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./nginx_proxy/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx_proxy/ssl/:/ssl/


  api-horario-onibus:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: api-horario-onibus
    env_file:
    - ./docker/.env
    restart: always
    depends_on:
    - nginx_proxy