version: "3.8"
services:
  web_server:
    build:
      context: docker
      dockerfile: ./Dockerfile
    container_name: api-horario-onibus
    restart: always
    ports:
      - 8080
    links: 
    - db  
  postgresql-db:
    build:
      context: database
      dockerfile: ./Dockerfile
    container_name: postgresql
    restart: always
