version: "3.8"
services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
    links:
    - node_api
    - postgresql_db

  node_api:
    build:
      context: docker
      dockerfile: ./Dockerfile
    container_name: api-horario-onibus
    restart: always
    links: 
    - postgresql_db
  
  postgresql_db:
    build:
      context: database
      dockerfile: ./Dockerfile
    container_name: postgresql
    restart: always
