version: "3.8"
services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./nginx_proxy/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx_proxy/ssl/:/ssl/
    links:
    - api-horario-onibus
    - db_lobato-conecta
    depends_on:
    - api-horario-onibus

  api-horario-onibus:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: api-horario-onibus
    env_file:
    - ./docker/.env
    restart: always
    links:
    - db_lobato-conecta
    depends_on:
    - db_lobato-conecta
  
  db_lobato-conecta:
    build:
      context: database
      dockerfile: ./Dockerfile
    container_name: db_lobato-conecta
    restart: always
